from os import environ

ENDPOINT_DOG_FACE_CROPPER = environ.get('ENDPOINT_DOG_FACE_CROPPER')

ENDPOINT_TENSORFLOW_MODEL = environ.get('ENDPOINT_TENSORFLOW_MODEL')
ENDPOINT_TENSORFLOW_MODEL = 'http://localhost:5000/predict?'

ENDPOINT_REPORTAR_MASCOTA = environ.get('ENDPOINT_REPORTAR_MASCOTA')

REPOSITORIO_DE_IMAGENES_PUBLICAS = environ.get('REPOSITORIO_DE_IMAGENES_PUBLICAS')

# Base de datos
DB_URI = environ.get('MONGODB_URL')
