import os

ENDPOINT_DOG_FACE_CROPPER = os.environ.get('ENDPOINT_DOG_FACE_CROPPER')

ENDPOINT_TENSORFLOW_MODEL = os.environ.get('ENDPOINT_TENSORFLOW_MODEL')

ENDPOINT_REPORTAR_MASCOTA = os.environ.get('ENDPOINT_REPORTAR_MASCOTA')

REPOSITORIO_DE_IMAGENES_PUBLICAS = os.environ.get('REPOSITORIO_DE_IMAGENES_PUBLICAS')



